### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bwinton** [Osmose/atom-dxr-search#1]
Steps to reproduce:
1. Cmd-Alt-J
2. type "makeWidgetId" and hit enter.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [atom-dxr-search](https://github.com/Osmose/atom-dxr-search) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/bwinton/Programming/atom/atom-dxr-search/lib/atom-dxr-search-view.coffee:149

TypeError: Cannot read property 'length' of undefined
  at Object.$.ajax.success (/Users/bwinton/Programming/atom/atom-dxr-search/lib/atom-dxr-search-view.coffee:149:63)
  at fire (/Users/bwinton/Programming/atom/atom-dxr-search/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3099:30)
  at Object.self.fireWith [as resolveWith] (/Users/bwinton/Programming/atom/atom-dxr-search/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:3211:7)
  at done (/Users/bwinton/Programming/atom/atom-dxr-search/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8264:14)
  at XMLHttpRequest.<anonymous> (/Users/bwinton/Programming/atom/atom-dxr-search/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:8605:9)

```
### Commands

```
     -0:43.8.0 core:close (atom-pane.pane.active)
     -0:40.9.0 atom-dxr-search:toggle (atom-text-editor.editor.is-focused)
     -0:35 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:26 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:07.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:07.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 atom-dxr-search:toggle (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "speedkills",
      "metrics",
      "build-markdown",
      "build-markdown",
      "build-markdown"
    ]
  },
  "atom-dxr-search": {}
}
```
### Installed Packages

``` coffee
# User
atom-dxr-search, v0.1.2
atom-whimsy, v0.1.1
build, v0.47.0
emmet, v2.3.13
language-diff, v0.3.1
linter, v1.7.2
linter-csslint, v1.0.6
linter-eslint, v3.0.2
linter-less, v2.1.0
linter-pep8, v1.0.1
minimap, v4.13.4
minimap-linter, v1.0.0
wordcount, v2.3.0

# Dev
bracket-matcher, v0.76.0
```

**Comment by Osmose** [comment]
Fixed and published!
